### ISSUE TITLE
npm WARN custom-login@0.0.0 No repository field

### ISSUE THREAD

**Issue by KenBarr** [auth0-samples/auth0-javascript-samples#44] opened 2018-04-20 18:43 UTC
When trying to clone and run 01-Login example I see both install and execution errors wrt custom-login.
 
Step:
git clone https://github.com/auth0-samples/auth0-javascript-samples.git
cd auth0-javascript-samples/01-Login/
cp auth0-variables.js.example auth0-variables.js
 vi auth0-variables.js   <-  Fix AUTH0_CLIENT_ID and AUTH0_DOMAIN
 npm install
       This step finishes with:   **npm WARN custom-login@0.0.0 No repository field**
sudo ln -s /usr/bin/nodejs /usr/bin/node
        Fix for legacy invocation of nodejs in scripts
npm start
       This step fails with: 

 npm start          
> custom-login@0.0.0 start /home/ubuntu/auth0-javascript-samples/01-Login
> serve -p 3000

/home/ubuntu/auth0-javascript-samples/01-Login/node_modules/serve/bin/serve.js:11
const { coroutine } = require('bluebird')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-1054-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! custom-login@0.0.0 start: `serve -p 3000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the custom-login@0.0.0 start script 'serve -p 3000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the custom-login package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     serve -p 3000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs custom-login
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls custom-login
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/auth0-javascript-samples/01-Login/npm-debug.log

ubuntu@ip-172-31-57-212:~/auth0-javascript-samples/01-Login$ npm owner ls custom-login
npm ERR! owner ls Couldn't get owner data custom-login
npm ERR! Linux 4.4.0-1054-aws
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "owner" "ls" "custom-login"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/custom-login
npm ERR! 404
npm ERR! 404  'custom-login' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/auth0-javascript-samples/01-Login/npm-debug.log
[npm-debug.log](https://github.com/auth0-samples/auth0-javascript-samples/files/1933261/npm-debug.log)

**Comment by jimmyjames** [comment] 2019-06-24 19:37
I'm not able to reproduce this issue, and given the sample has changed since the time of reporting, going to close it. If you're still seeing the issue, please reopen and include any additional information as required. Thanks!

**Closed by jimmyjames** 2019-06-24 19:37 UTC
